from py_testgen_app.src.Copilot.Kruskal.PromptOnly.T8.kruskal import Kruskal

import unittest

class KruskalTest(unittest.TestCase):
    def setUp(self):
        self.kruskal = Kruskal(7)
        self.kruskal2 = Kruskal(5)
        self.kruskal3 = Kruskal(5)
        self.kruskal4 = Kruskal(5)
        self.kruskal5 = Kruskal(5)
        self.kruskal6 = Kruskal(5)
        self.kruskal7 = Kruskal(5)
        self.kruskal8 = Kruskal(5)
        self.kruskal9 = Kruskal(5)
        self.kruskal10 = Kruskal(5)
        self.kruskal11 = Kruskal(5)
        self.kruskal12 = Kruskal(5)
        self.kruskal13 = Kruskal(5)
        self.kruskal14 = Kruskal(5)
        self.kruskal15 = Kruskal(5)
        self.kruskal16 = Kruskal(5)
        self.kruskal17 = Kruskal(5)
        self.kruskal18 = Kruskal(5)
        self.kruskal19 = Kruskal(5)
        self.kruskal20 = Kruskal(5)
        self.kruskal21 = Kruskal(5)
        self.kruskal22 = Kruskal(5)
        self.kruskal23 = Kruskal(5)
        self.kruskal24 = Kruskal(5)
        self.kruskal25 = Kruskal(5)
        self.kruskal26 = Kruskal(5)
        self.kruskal27 = Kruskal(5)
        self.kruskal28 = Kruskal(5)
        self.kruskal29 = Kruskal(5)
        self.kruskal30 = Kruskal(5)
        self.kruskal31 = Kruskal(5)
        self.kruskal32 = Kruskal(5)
        self.kruskal33 = Kruskal(5)
        self.kruskal34 = Kruskal(5)
        self.kruskal35 = Kruskal(5)
        self.kruskal36 = Kruskal(5)
        self.kruskal37 = Kruskal(5)
        self.kruskal38 = Kruskal(5)